FROM ubuntu:14.04

ENV LANG C.UTF-8

RUN apt-get update && apt-get install curl bzip2 git -y --fix-missing

RUN curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash miniconda.sh -f -b -p /opt/anaconda
ENV PATH /opt/anaconda/bin:$PATH
RUN conda install dask distributed drmaa nomkl pytest mock ipython pip psutil -c conda-forge

COPY ./setup-slave.sh /
COPY ./run-slave.sh /
RUN bash ./setup-slave.sh

CMD python -m SimpleHTTPServer
