FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install curl bzip2 -y
RUN curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
RUN bash miniconda.sh -f -b -p /opt/anaconda
ENV PATH /opt/anaconda/bin:$PATH
COPY ./setup-slave.sh /
COPY ./run-slave.sh /
RUN bash ./setup-slave.sh

CMD python -m SimpleHTTPServer
